services:
  - type: web
    name: eye-heart-backend
    env: python
    region: oregon
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    pythonVersion: 3.11  # ✅ required for TensorFlow compatibility
